[build]
  command = "BYPASS_WORDPRESS=true yarn build:netlify"
  publish = "public"
  
  # The build:netlify script automatically ensures directories exist
  # using the scripts/ensure-directories.js script which creates 
  # static/audio with placeholder files if needed

[build.environment]
  NODE_VERSION = "20.19.0"
  BYPASS_WORDPRESS = "true"
  NPM_FLAGS = "--prefer-offline --no-audit"
  YARN_FLAGS = "--prefer-offline --no-audit"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[plugins]]
  package = "@netlify/plugin-gatsby"
